version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - 8001:8000
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    networks:
      - laravel
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: notification_system
      DB_USERNAME: omar
      DB_PASSWORD: 1234

      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: notification_system
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: omar
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - 6379:6379
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
  